// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WifiWarriorAPI.Data;

#nullable disable

namespace WifiWarriorAPI.Migrations
{
    [DbContext(typeof(ApiDbContext))]
    [Migration("20221119155701_UpdateRelationships")]
    partial class UpdateRelationships
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WifiWarriorAPI.Models.Address", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AddressLine1")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AddressLine2")
                        .HasColumnType("text");

                    b.Property<string>("Area")
                        .HasColumnType("text");

                    b.Property<long?>("ConnectionInformationId")
                        .HasColumnType("bigint");

                    b.Property<string>("County")
                        .HasColumnType("text");

                    b.Property<long>("CreatedById")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Postcode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Status")
                        .HasColumnType("integer");

                    b.Property<long?>("UpdatedById")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long>("VenueId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ConnectionInformationId");

                    b.HasIndex("VenueId");

                    b.ToTable("Addresses");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            AddressLine1 = "Address Line 1",
                            AddressLine2 = "Address Line 2",
                            Area = "Area",
                            ConnectionInformationId = 1L,
                            County = "County",
                            CreatedById = 1L,
                            CreatedDate = new DateTime(2022, 11, 19, 15, 57, 0, 917, DateTimeKind.Local).AddTicks(290),
                            Latitude = 0.10000000000000001,
                            Longitude = 0.10000000000000001,
                            Postcode = "Postcode",
                            Status = 1,
                            VenueId = 1L
                        });
                });

            modelBuilder.Entity("WifiWarriorAPI.Models.ConnectionInformation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ConnectionTypeId")
                        .HasColumnType("bigint");

                    b.Property<long>("CreatedById")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("Status")
                        .HasColumnType("integer");

                    b.Property<long?>("UpdatedById")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long?>("WifiLoginDetailsId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ConnectionTypeId")
                        .IsUnique();

                    b.HasIndex("WifiLoginDetailsId")
                        .IsUnique();

                    b.ToTable("ConnectionInformation");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            ConnectionTypeId = 2L,
                            CreatedById = 1L,
                            CreatedDate = new DateTime(2022, 11, 19, 15, 57, 0, 917, DateTimeKind.Local).AddTicks(280),
                            Status = 1,
                            WifiLoginDetailsId = 1L
                        });
                });

            modelBuilder.Entity("WifiWarriorAPI.Models.ConnectionType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CreatedById")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Status")
                        .HasColumnType("integer");

                    b.Property<long?>("UpdatedById")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("ConnectionTypes");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedById = 1L,
                            CreatedDate = new DateTime(2022, 11, 19, 15, 57, 0, 917, DateTimeKind.Local).AddTicks(220),
                            Name = "Open",
                            Status = 1
                        },
                        new
                        {
                            Id = 2L,
                            CreatedById = 1L,
                            CreatedDate = new DateTime(2022, 11, 19, 15, 57, 0, 917, DateTimeKind.Local).AddTicks(250),
                            Name = "Password",
                            Status = 1
                        },
                        new
                        {
                            Id = 3L,
                            CreatedById = 1L,
                            CreatedDate = new DateTime(2022, 11, 19, 15, 57, 0, 917, DateTimeKind.Local).AddTicks(250),
                            Name = "Login",
                            Status = 1
                        });
                });

            modelBuilder.Entity("WifiWarriorAPI.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Email = "Test@email.com",
                            FirstName = "TestName",
                            LastName = "TestLastName",
                            Password = "UserPassword",
                            Username = "TestUsername"
                        });
                });

            modelBuilder.Entity("WifiWarriorAPI.Models.Venue", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CreatedById")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Status")
                        .HasColumnType("integer");

                    b.Property<long?>("UpdatedById")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("Venues");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedById = 1L,
                            CreatedDate = new DateTime(2022, 11, 19, 15, 57, 0, 917, DateTimeKind.Local).AddTicks(300),
                            Name = "Venue Name",
                            Status = 1
                        });
                });

            modelBuilder.Entity("WifiWarriorAPI.Models.WifiLoginDetails", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CreatedById")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Ssid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Status")
                        .HasColumnType("integer");

                    b.Property<long?>("UpdatedById")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("WifiLoginDetails");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedById = 1L,
                            CreatedDate = new DateTime(2022, 11, 19, 15, 57, 0, 917, DateTimeKind.Local).AddTicks(270),
                            Password = "Password",
                            Ssid = "SSID",
                            Status = 1
                        });
                });

            modelBuilder.Entity("WifiWarriorAPI.Models.Address", b =>
                {
                    b.HasOne("WifiWarriorAPI.Models.ConnectionInformation", "ConnectionInformation")
                        .WithMany()
                        .HasForeignKey("ConnectionInformationId");

                    b.HasOne("WifiWarriorAPI.Models.Venue", "Venue")
                        .WithMany("Addresses")
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ConnectionInformation");

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("WifiWarriorAPI.Models.ConnectionInformation", b =>
                {
                    b.HasOne("WifiWarriorAPI.Models.ConnectionType", "ConnectionType")
                        .WithOne("ConnectionInformation")
                        .HasForeignKey("WifiWarriorAPI.Models.ConnectionInformation", "ConnectionTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WifiWarriorAPI.Models.WifiLoginDetails", "WifiLoginDetails")
                        .WithOne("ConnectionInformation")
                        .HasForeignKey("WifiWarriorAPI.Models.ConnectionInformation", "WifiLoginDetailsId");

                    b.Navigation("ConnectionType");

                    b.Navigation("WifiLoginDetails");
                });

            modelBuilder.Entity("WifiWarriorAPI.Models.ConnectionType", b =>
                {
                    b.Navigation("ConnectionInformation")
                        .IsRequired();
                });

            modelBuilder.Entity("WifiWarriorAPI.Models.Venue", b =>
                {
                    b.Navigation("Addresses");
                });

            modelBuilder.Entity("WifiWarriorAPI.Models.WifiLoginDetails", b =>
                {
                    b.Navigation("ConnectionInformation")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
